site_name: redash-python
site_url: ""
site_description: A more complete Python library for Redash
site_author: Blacksuan19

repo_url: https://github.com/blacksuan19/redash-python

theme:
    name: material
    palette:
      scheme: preference
      primary: deep-lue
      accent: deep-purple
    icon:
      logo: fontawesome/solid/code
    highlightjs: true
    hljs_languages:
        - yaml
        - python
        - bash
    features:
        - navigation.instant
        - navigation.sections
        - navigation.top
        - search.suggest
        - search.highlight
        - search.share
        - offline
    
    shortcuts: 
      help: 191    # ?
      next: 78     # n
      previous: 80 # p
      search: 83   # s

markdown_extensions:
    - markdown.extensions.footnotes
    - markdown.extensions.meta
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde


plugins:
    - search
    - minify:
        minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/Blacksuan19/redash-python
      name: redash-python on github
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/redash-python
      name: redash-python on pypi
  generator: false

copyright: Copyright &copy; 2022 <a href="https://blacksuan19.dev">Blacksuan19</a>.

nav:
- Home: index.md
- API Documentation:
    - Alerts: api/services/alerts.md
    - Base: api/services/base.md
    - Dashboards: api/services/dashboards.md
    - Data Sources: api/services/data_sources.md
    - Destinations: api/services/destinations.md
    - Groups: api/services/groups.md
    - Mixins: api/services/mixins.md
    - Queries: api/services/queries.md
    - Query Snippets: api/services/query_snippets.md
    - Redash: api/redash.md
    - Users: api/services/users.md
    - Widgets: api/services/widgets.md
- Examples: 
    - Archive User: examples/archive_user.md
