name: Build and Publish Docs

on:
  push:      
  workflow_dispatch:

   
jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with: { python-version: "3.10" }

    - name: Install dependencies
      run: pip install -r docs/requirements.txt

    - name: Build documentation
      run: cd docs && novella

    - name: Upload documentation
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs/_site

  docs-publish:
    needs: [ build_docs ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: docs
        path: docs/_site

    - name: Publish docs
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: docs/_site
        ssh-key: ${{ secrets.DEPLOY_KEY }}