name: Release and Publish wheel package

on:
  push:
    tags:
      - '*'
      
  workflow_dispatch:

jobs:
  build_wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - name: Install dependecies
        run: |
          python -m pip install -U pip wheel setuptools build twine 
          python -m pip install "redash-python[dev]"
      - name: Build wheel package
        run: python -m build

      - name: Release wheel package
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "Latest Stable Build"
          files: |
            dist/*.whl

      - name: Upload artifact to action
        uses: actions/upload-artifact@v3
        with:
          name: Wheel Package
          path: dist/*.whl

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}


  build_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with: { python-version: "3.10" }

    - name: Install dependencies
      run: pip install -r docs/requirements.txt

    - name: Build documentation
      run: cd docs && novella

    - name: Upload documentation
    - uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs/_site

  docs-publish:
    needs: [ build_docs ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: docs
        path: docs/_site
    - name: Publish docs
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: docs/_site
        ssh-key: ${{ secrets.DEPLOY_KEY }}

