name: Build installable wheel package

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"

  workflow_dispatch:

jobs:
  build_wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - name: Install dependecies
        run: |
          python -m pip install -U pip wheel setuptools build twine 
          python -m pip install -r requirements.txt

      - name: Build wheel package
        run: python -m build

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            dist/*.whl

      - name: Upload artifact to action
        uses: actions/upload-artifact@v3
        with:
          name: Wheel Package
          path: dist/*.whl

      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
